service: my-express-application

provider:
  name: aws
  runtime: nodejs14.x
  stage: "${opt:stage, 'development'}"
  region: "${opt:region, 'us-east-2'}"

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
